- name: Prepare all nodes
  hosts: all
  become: true
  vars_files:
    - vars.yml
  roles:
    - dependencies

- name:  ⁠Bootstrap kubernetes cluster
  hosts: "{{ master_nodes[0] }}"
  become: true
  vars_files:
    - vars.yml
  roles:
    - bootstrap_master

- name: Get Kubernetes join token
  hosts: "{{ master_nodes[0] }}"
  become: true
  vars_files:
    - vars.yml
  roles:
    - get_token

- name: Setup kubernetes masters
  hosts: all
  become: true
  vars_files:
    - vars.yml
  roles:
    - setup_masters