all:
  hosts:
    k8s-master-1:
      ansible_host: ${{ secrets.MASTER }}
      ansible_user: root
      ansible_ssh_private_key_file: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}

    k8s-master-2:
      ansible_host: "{{ secrets.SECONDARY_MASTERS.split(',')[0] }}"
      ansible_user: root
      ansible_ssh_private_key_file: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}

    k8s-master-3:
      ansible_host: "{{ secrets.SECONDARY_MASTERS.split(',')[1] }}"
      ansible_user: root
      ansible_ssh_private_key_file: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}
  vars:
    ansible_python_interpreter: /usr/bin/python3
