---
- name: Define variables
  set_fact:
    master_node_ip: "{{ lookup('vars', 'k8s_master_1_host') }}"

- name: Reset the Kubernetes setup if any
  ansible.builtin.command: kubeadm reset -f
  ignore_errors: yes
  become: true

- name: Remove existing Kubernetes configuration and data
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes/
    - /var/lib/etcd
  become: true

- name: Ensure required sysctl settings
  ansible.builtin.command: >
    sysctl net.bridge.bridge-nf-call-iptables=1
  become: true

- name: Pull required Kubernetes images
  ansible.builtin.command: kubeadm config images pull
  become: true
  
- name: Initialize the cluster (this could take some time)
  ansible.builtin.command: >
    kubeadm init
    --apiserver-advertise-address={{ master_node_ip }}
    --control-plane-endpoint={{ master_node_ip }}:6443
    --pod-network-cidr=10.244.0.0/16
    --upload-certs
    --ignore-preflight-errors=all
  args:
    creates: cluster_initialized.log
  become: true
- name: Create .kube directory
  become: true
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    mode: '0755'
 
- name: Copy admin.conf to user's kube config
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: true
    mode: '0644'

- name: Install Pod network
  become: true
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  args:
    chdir: /home
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config
  register: pod_network_setup_log
