---
- name: Load join command from file
  ansible.builtin.slurp:
    src: /tmp/join_command.txt
  register: join_command_file
  delegate_to: k8s-master-1


- name: Check if the node is already part of the cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- name: Set join command
  ansible.builtin.set_fact:
    join_command: "{{ join_command_file.content | b64decode }}"
  when: join_command is defined and join_command != '' and not kubelet_conf_stat.stat.exists


- name: Delete join command file
  ansible.builtin.file:
    path: /tmp/join_command.txt
    state: absent
  delegate_to: k8s-master-1


- name: Join cluster as control plane
  ansible.builtin.command: "{{ join_command }}"
  timeout: 60
  when: join_command is defined and join_command != '' and not kubelet_conf_stat.stat.exists

  changed_when: false
- name: Enable and start Kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    state: started
  when: join_command is defined and join_command != '' and not kubelet_conf_stat.stat.exists
  
- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'
  become: true
  when: join_command is defined and join_command != '' and not kubelet_conf_stat.stat.exists

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: '0644'
  become: true
  when: join_command is defined and join_command != '' and not kubelet_conf_stat.stat.exists

- name: Install Pod network
  become: true
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  args:
    chdir: /root
  environment:
    KUBECONFIG: /root/.kube/config
  register: pod_network_setup_log
  changed_when: "'configured' in pod_network_setup_log.stdout"

