---
- name: Check if join token exists
  ansible.builtin.command:
    cmd: kubeadm token list
  register: kubeadm_token_list
  changed_when: false

- name: Get join command
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: join_command_raw
  when: kubeadm_token_list.stdout_lines | length == 0
  changed_when: join_command_raw.stdout != ""

- name: Get existing join command
  ansible.builtin.command:
    cmd: kubeadm token list | tail -n 1 | awk '{print "kubeadm join --token", $1, $2}'
  register: join_command_raw
  when: kubeadm_token_list.stdout_lines | length > 0
  changed_when: false

- name: Set join command
  ansible.builtin.set_fact:
    join_command: "{{ join_command_raw.stdout }}"
