---
- name: Enable and start Kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    state: started

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'
  become: true

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: '0644'
  become: true
