name: Deploy Kubernetes Cluster
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    outputs:
      bootstrap_master: ${{ steps.getHosts.outputs.bootstrap_master }}
      masters: ${{ steps.getHosts.outputs.masters }}
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python3 -m pip install -r requirements.txt

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}

    - name: Split Hosts
      id: getHosts
      run: |
        HOSTS="${{ secrets.HOSTS }}"
        IFS=';' read -r -a ADDR_ARRAY <<< "$HOSTS"
        BOOTSTRAP_MASTER=${ADDR_ARRAY[0]}
        MASTERS=$(IFS=';'; echo "${ADDR_ARRAY[*]:1}")
        
        echo "bootstrap_master=$BOOTSTRAP_MASTER" >> $GITHUB_OUTPUT
        echo "masters=$MASTERS" >> $GITHUB_OUTPUT

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh
        
    - name: Add SSH known_hosts
      run: |
        ssh-keyscan -H ${{ steps.getHosts.outputs.bootstrap_master }} >> ~/.ssh/known_hosts 
        IFS=';' read -r -a array <<< "${{ steps.getHosts.outputs.masters }}"
        for element in "${array[@]}"
        do
            ssh-keyscan -H $element >> ~/.ssh/known_hosts
        done

    - name: Write SSH private key to file
      run: |
        echo "${{ secrets.HETZNER_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/hetzner
        chmod 600 ~/.ssh/hetzner

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: |
        ansible-playbook --user root -i inventory/hosts.yaml cluster.yml --extra-vars '{
          "ansible_ssh_private_key_file": "~/.ssh/hetzner",
          "k8s_master_1_host": "${{ steps.getHosts.outputs.bootstrap_master }}",
          "k8s_master_masters": "${{ steps.getHosts.outputs.masters }}"
        }'